const About = () => {
    return (
        <div className="w-100 d-flex justify-content-center">
            <div style={{ "max-width": "50vw" }}>
                <p style={{ "whitepace": "pre-line" }}></p>
                <p>
                    Terms of Use
                    All text generated by the meme generator is derived from free-to-access user-created content at imgflip.com. MarkovianMemes is not responsible for any of the content generated by the generator, or any other content created by website users.
                    The images on this website are used under “fair use” (US) / “right to quote” (EU).
                    You may use our webpage and their contents for private, non-commercial use only.
                    The properties of these pages, including without limitation, the appearance, contents, access and availability, the services and goods supplied, and the rules of use, are subject to change by us, at any time, for any reason and without prior notice.
                    The terms of use of our pages are governed by the laws of Finland.
                    Copyright © 2021. MarkovianMemes


        </p>
            </div>
        </div>
    )
}

export default About